version: '3'

services:
  eshopwcfservice:
    environment:
      - ConnectionString=Server=sql.data;Database=eShopDatabase;User Id=sa;Password=Pass@word
    ports:
     - "5113:80"
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Pass@word", "-Q", "select 1" ]
      interval: 1s
      retries: 20
networks:
  default:
    external:
      name: nat
